version: "3.9"
services:
  app:
    container_name: hvbn-app
    build: ./infra/php
    volumes:
      - ./src:/work

  web:
    container_name: hvbn-web
    image: nginx:1.20-alpine
    ports:
      - 8088:80
    volumes:
      - ./src:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    container_name: hvbn-db
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 33063:3306

volumes:
  db-store: